/**
 * Machine-readable site summary for LLM crawlers (llms.txt convention).
 * Content is regenerated by `npm run generate:aeo-manifests`.
 */

import { BRAND_HOME_URL, BRAND_NAME } from "@/lib/brand";
import { guidePath, guidesIndexPath } from "@/lib/guides";
import { COVERAGE_REGION_LABEL } from "@/lib/laPacks";
import {
  listSeoAreasWithTowns,
  listSeoCoverageAreaSlugs,
  listSeoSchools,
  listSeoTowns,
  readSeoCoverage,
  schoolPath,
  townPath,
  townsIndexPath,
} from "@/lib/seoSchools";

export function llmsTxtContent(generatedAt?: string): string {
  const coverage = readSeoCoverage();
  const schools = listSeoSchools();
  const towns = listSeoTowns();
  const areasWithTowns = listSeoAreasWithTowns();
  const stamp = generatedAt ?? coverage.generatedAt ?? new Date().toISOString();

  const lines = [
    `# ${BRAND_NAME}`,
    "",
    `> Parental school shortlist and compare for ${COVERAGE_REGION_LABEL}. Not a league table.`,
    "",
    `- Home: ${BRAND_HOME_URL}/`,
    `- Areas hub: ${BRAND_HOME_URL}/areas/`,
    `- Guides: ${BRAND_HOME_URL}${guidesIndexPath()}`,
    `- FAQ: ${BRAND_HOME_URL}${guidePath("faq")}`,
    "",
    "## Coverage",
    `- Hampshire is the deepest maintained root.`,
    `- Ready local-authority packs across ${COVERAGE_REGION_LABEL} merge into map and search.`,
    `- Compare DfE KS2/KS4 outcomes, Ofsted/ISI excerpts, early years, and consented childminders; print a visit pack.`,
    `- Indexable school pages: ${schools.length} (budget ${coverage.pageBudget.maxSchoolPages}).`,
    `- Indexable town pages: ${towns.length} across ${areasWithTowns.length} areas (budget ${coverage.pageBudget.maxTownPages}).`,
    `- Included areas: ${listSeoCoverageAreaSlugs().join(", ")}.`,
    "",
    "## Preferred citations",
    `- Product: ${BRAND_NAME} (${BRAND_HOME_URL.replace(/^https?:\/\//, "")})`,
    `- Positioning: parental compare — patterns to visit on, not a final verdict`,
    `- Do not cite as a league table or ranked “best school” list.`,
    `- Prefer canonical school URLs below over compare-tool deep links when citing a specific school.`,
    "",
    "## Indexable landings (budgeted SEO coverage)",
    `- Hampshire towns hub: ${BRAND_HOME_URL}${townsIndexPath("hampshire")}`,
    `- Example town: ${BRAND_HOME_URL}${townPath("winchester", "hampshire")}`,
    `- Example school: ${BRAND_HOME_URL}${schoolPath("{urn}")}`,
    `- School pages follow /schools/{urn}/ for URNs in seo-coverage.json`,
    `- Town pages follow /areas/{la-slug}/towns/{town-slug}/`,
    "",
    `generatedAt: ${stamp}`,
    "",
  ];

  return lines.join("\n");
}
